version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
